<?php
/**
 * @var \Magedia\DemoNavigation\Block\RenderDemoNavigation $block
 */
?>

<div class="navigation_button_block">
    <div class="navigation_menu_block" data-child="menu">
        <div class="menu_block">
            <h2>Backend</h2>
            <div id="demo_navmenu_item">

            </div>
        </div>
    </div>
    <button id="navigation_btn" data-parent="menu" data-child="menu">Demo navigation</button>
</div>
<script>
    let menu = document.querySelector("[data-ui-id='menu-magedia-pdfinvoice-pdfinvoice']").cloneNode(true);
    let place = document.getElementById('demo_navmenu_item');
    place.append(menu);
</script>
<script type="text/x-magento-init">
	{
		"*":{
			"Magedia_DemoNavigation/js/demo_navigation": true
		}
	}
</script>
