<?php
/** @var \Magedia\DemoNavigation\Block\RenderDemoNavigation $block */
/** @var \Magento\Framework\Escaper $escaper */

$marketplaceUrl = 'https://marketplace.magento.com/magedia-m2-pdf-invoice.html';
$guideLink = 'https://docs.magedia.com/user-guide/pdf-invoice/';
$manageTemplatesLink = '/magedia_pdfinvoice/template/index/';
$configLink = '/admin/system_config/edit/section/magedia_pdfinvoice/';
?>

<div class="navigation_button_block">
    <div class="navigation_menu_block" data-child="menu">
        <div class="menu_block">
            <h2>Backend</h2>
            <div id="demo_navmenu_item">
                <?php if($block->isFrontend()): ?>
                    <li data-ui-id="menu-magedia-pdfinvoice-pdfinvoice-front" class="item-pdfinvoice  parent  level-1" role="menu-item">
                        <strong class="submenu-group-title" role="presentation">
                            <span>PDF Invoice</span>
                        </strong>
                        <div class="submenu">
                            <ul role="menu">
                                <li data-ui-id="menu-magedia-pdfinvoice-pdfinvoice-manage" class="item-pdfinvoice-manage level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) . $manageTemplatesLink ?>" class="">
                                        <span>Manage Templates</span>
                                    </a>
                                </li>
                                <li data-ui-id="menu-magedia-pdfinvoice-pdfinvoice-configuration" class="item-pdfinvoice-configuration level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) . $configLink?>" class="">
                                        <span>Configuration</span>
                                    </a>
                                </li>
                                <li data-ui-id="menu-magedia-pdfinvoice-pdfinvoice-userguide" class="item-pdfinvoice-userguide level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($guideLink) ?>" target="_blank" class="">
                                        <span>User Guide</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                <?php endif; ?>
            </div>
            <div class="more-info">
                <p class="ready-to-purchase">Ready to purchase this extension?</p>
                <a class="configure-and-buy action-primary" href="<?= $escaper->escapeUrl($marketplaceUrl); ?>">Configure and buy</a>
                <a class="back-to-product-page" href="<?= $escaper->escapeUrl($marketplaceUrl); ?>">Back to product page</a>
            </div>
        </div>
    </div>
    <button id="navigation_btn" data-parent="menu" data-child="menu">
        Demo navigation
        <div class="navigation-button-arrows">
            <i class="arrow"></i>
            <i class="arrow"></i>
        </div>
    </button>
</div>
<script>
    let menu = document.querySelector("[data-ui-id='menu-magedia-pdfinvoice-pdfinvoice']").cloneNode(true);
    let place = document.getElementById('demo_navmenu_item');
    place.append(menu);
</script>
<script type="text/x-magento-init">
	{
		"*":{
			"Magedia_DemoNavigation/js/demo_navigation": true
		}
	}
</script>


