<?php
/** @var \Magedia\DemoNavigation\Block\RenderDemoNavigation $block */
/** @var \Magento\Framework\Escaper $escaper */

$marketplaceUrl = 'https://marketplace.magento.com/magedia-m2-pdf-invoice.html';
$guideLink = '';
$ruleSettingsLink = '/magedia_acart/rule/index/';
$mailJournalLink = '/magedia_acart/mailjournal/index/';
$statisticLink = '/magedia_acart/statistic/index/';
$stockLink = '/magedia_acart/stock/index/';
$configLink = '/admin/system_config/edit/section/magedia_acart/';
?>

<div class="navigation_button_block">
    <div class="navigation_menu_block" data-child="menu">
        <div class="menu_block">
            <h2>Backend</h2>
            <div id="demo_navmenu_item">
                <?php if($block->isFrontend()): ?>
                    <li data-ui-id="menu-magedia-abandonedcart-acart-front" class="item-abandonedcart  parent  level-1" role="menu-item">
                        <strong class="submenu-group-title" role="presentation">
                            <span>Abandoned Cart</span>
                        </strong>
                        <div class="submenu">
                            <ul role="menu">
                                <li data-ui-id="menu-magedia-abandonedcart-acart-rule" class="item-abandonedcart-rule level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) . $ruleSettingsLink ?>" class="">
                                        <span>Rule Settings</span>
                                    </a>
                                </li>
                                <li data-ui-id="menu-magedia-abandonedcart-acart-mailjournal" class="item-abandonedcart-mailjournal level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) . $mailJournalLink ?>" class="">
                                        <span>Mail Journal</span>
                                    </a>
                                </li>
                                <li data-ui-id="menu-magedia-abandonedcart-acart-statistic" class="item-abandonedcart-statistic level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) . $statisticLink ?>" class="">
                                        <span>Statistic</span>
                                    </a>
                                </li>
                                <li data-ui-id="menu-magedia-abandonedcart-acart-stock" class="item-abandonedcart-stock level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) . $stockLink ?>" class="">
                                        <span>Stock</span>
                                    </a>
                                </li>
                                <li data-ui-id="menu-magedia-abandonedcart-acart-configuration" class="item-abandonedcart-configuration level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) . $configLink ?>" class="">
                                        <span>Configuration</span>
                                    </a>
                                </li>
                                <li data-ui-id="menu-magedia-abandonedcart-acart-userguide" class="item-abandonedcart-userguide level-2" role="menu-item">
                                    <a href="<?= $escaper->escapeUrl($block->getAdminUrl()) ?>" target="_blank" class="">
                                        <span>User Guide</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                <?php endif; ?>
            </div>
            <div class="more-info">
                <p class="ready-to-purchase">Ready to purchase this extension?</p>
                <a class="configure-and-buy action-primary" href="<?= $escaper->escapeUrl($marketplaceUrl); ?>">Configure and buy</a>
                <a class="back-to-product-page" href="<?= $escaper->escapeUrl($marketplaceUrl); ?>">Back to product page</a>
            </div>
        </div>
    </div>
    <button id="navigation_btn" data-parent="menu" data-child="menu">
        Demo navigation
        <div class="navigation-button-arrows">
            <i class="arrow"></i>
            <i class="arrow"></i>
        </div>
    </button>
</div>
<script>
    let menu = document.querySelector("[data-ui-id='menu-magedia-abandonedcart-acart']").cloneNode(true);
    let place = document.getElementById('demo_navmenu_item');
    place.append(menu);
</script>
<script type="text/x-magento-init">
	{
		"*":{
			"Magedia_DemoNavigation/js/demo_navigation": true
		}
	}
</script>


